# Generated by Django 5.0.12 on 2025-07-24 15:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_author_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='secret_key',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
    ]
